---
title: "Calibration Values"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    number_sections: true
    smart: false
params:
  path_df: ""
  context: "hpc"
---

```{r setup, include = FALSE}
source("R/shared_variables.R", local = TRUE)

library(dplyr)
library(EpiModelHIV)

context <- params$context
source("R/netsim_settings.R", local = TRUE)
source("R/C-calibration/utils-calib_plots.R", local = TRUE)

d_outs <- readRDS(params$path_df) |>
  EpiModelHIV::mutate_calibration_targets()

targets <- EpiModelHIV::get_calibration_targets()
races_names <- c("B", "H", "W")
races <- 1:3

med_iqr <- function(x, fmtr) {
  vs <- quantile(x, c(0.5, 0.25, 0.75)) |> fmtr()
  paste0(vs[1], " [", vs[2], "-",  vs[3], "]")
}
```

## cc.dx - section 7.1

```{r}
p <- calib_plot_infos[["cc.dx"]]
make_calib_plot(d_outs, p)
```

```{r}
col_names <- paste0(c("Black", "Hispanic", "White/Other"), "MSM")
row_names <- c(
  "Target Statistic: Diagnosed Fraction",
  "Simulations: Diagnosed Fractions (med [IQR])",
  "Calibrated Rates (per Week)",
  "Mean Inter-Test Interval (Years)"
)

fmtr <- scales::label_percent(0.1)
tar_names <- paste0("cc.dx.", races_names)
tar <- targets[tar_names] |> fmtr()
p_names <- paste0("hiv.test.rate")
prms <- param[[p_names]] |> scales::label_scientific()()
m_int <- (1 / param[[p_names]] / year_steps) |> scales::label_number(0.1)()

sim_vals <- d_outs |>
  filter(time > max(time) - year_steps) |>
  select(sim, all_of(tar_names)) |>
  group_by(sim) |>
  summarise(across(everything(), mean)) |>
  select(-sim) |>
  summarise(across(everything(), \(x) med_iqr(x, fmtr))) |>
  as.character()

tbl <- rbind(tar, sim_vals,  prms, m_int)
rownames(tbl) <- row_names
colnames(tbl) <- col_names

knitr::kable(tbl)
```

## cc.vsupp - section 7.3

```{r}
p <- calib_plot_infos[["cc.vsupp"]]
make_calib_plot(d_outs, p)
```

```{r}
col_names <- paste0(c("Black", "Hispanic", "White/Other"), "MSM")
row_names <- c(
  "Target Statistic: Fraction VL Suppressed",
  "Simulations: Fraction VL Suppressed (med [IQR])",
  "Calibrated Halting Rates (per Week)",
  "Mean Time to First ART Stoppage (in Weeks)",
  "Mean Time to First ART Stoppage (in Years)"
)

fmtr <- scales::label_percent(0.1)
tar_names <- paste0("cc.vsupp.", races_names)
tar <- targets[tar_names] |> fmtr()
p_names <- paste0("tx.halt.rate")
prms <- param[[p_names]] |> scales::label_scientific()()
mean_time_stop_w <- scales::label_number(1)(1 / param[[p_names]])
mean_time_stop_y <- scales::label_number(0.1)(1 / param[[p_names]] / year_steps)


sim_vals <- d_outs |>
  filter(time > max(time) - year_steps) |>
  select(sim, all_of(tar_names)) |>
  group_by(sim) |>
  summarise(across(everything(), mean)) |>
  select(-sim) |>
  summarise(across(everything(), \(x) med_iqr(x, fmtr))) |>
  as.character()

tbl <- rbind(tar, sim_vals,  prms, mean_time_stop_w, mean_time_stop_y)
rownames(tbl) <- row_names
colnames(tbl) <- col_names

knitr::kable(tbl)
```

## i.prev.dx - section 8.2

```{r}
p <- calib_plot_infos[["i.prev.dx"]]
make_calib_plot(d_outs, p)
```

```{r}
col_names <- paste0(c("Black", "Hispanic", "White/Other"), "MSM")
row_names <- c(
  "Target Statistic: HIV Prevalence",
  "Simulations: HIV Prevalence (med [IQR])",
  "Transmission Scaler (per act)"
)

fmtr <- scales::label_percent(0.1)
tar_names <- paste0("i.prev.dx.", races_names)
tar <- targets[tar_names] |> fmtr()
p_names <- paste0("hiv.trans.scale")
prms <- param[[p_names]] |> scales::label_number(0.01)()

sim_vals <- d_outs |>
  filter(time > max(time) - year_steps) |>
  select(sim, all_of(tar_names)) |>
  group_by(sim) |>
  summarise(across(everything(), mean)) |>
  select(-sim) |>
  summarise(across(everything(), \(x) med_iqr(x, fmtr))) |>
  as.character()

tbl <- rbind(tar, sim_vals, prms)
rownames(tbl) <- row_names
colnames(tbl) <- col_names

knitr::kable(tbl)
```

## cc.prep - section xx

```{r}
p <- calib_plot_infos[["cc.prep"]]
make_calib_plot(d_outs, p)
```

```{r}
col_names <- paste0(c("Black", "Hispanic", "White/Other"), "MSM")
row_names <- c(
  "Target Statistic: PrEP Coverage",
  "Simulations: PrEP Coverage (med [IQR])",
  "Calibrated PrEP Rates (per Week)"
)

fmtr <- scales::label_percent(0.1)
tar_names <- paste0("cc.prep.", races_names)
tar <- targets[tar_names] |> fmtr()
p_names <- paste0("prep.start.rate")
prms <- param[[p_names]] |> scales::label_scientific()()

sim_vals <- d_outs |>
  filter(time > max(time) - year_steps) |>
  select(sim, all_of(tar_names)) |>
  group_by(sim) |>
  summarise(across(everything(), mean)) |>
  select(-sim) |>
  summarise(across(everything(), \(x) med_iqr(x, fmtr))) |>
  as.character()

tbl <- rbind(tar, sim_vals, prms)
rownames(tbl) <- row_names
colnames(tbl) <- col_names

knitr::kable(tbl)
```

## STI - section xx

```{r}
p <- calib_plot_infos[["ir100.sti"]]
make_calib_plot(d_outs, p)
```

```{r}
col_names <- paste0(c("gono", "chla", "syph"), " IR100")
row_names <- c(
  "Target Statistic: STI IR100",
  "Simulations: STI IR100 (med [IQR])",
  "Calibrated Transmission Urethral Probability (per act)"
)

fmtr <- scales::label_number(0.1)
tar_names <- c("ir100.gono", "ir100.chla", "ir100.syph")
tar <- targets[tar_names] |> fmtr()
p_names <- c("gono.uret.prob", "chla.uret.prob", "syph.prob")
prms <- unlist(param[p_names]) |> scales::label_number(0.01)()

sim_vals <- d_outs |>
  filter(time > max(time) - year_steps) |>
  select(sim, all_of(tar_names)) |>
  group_by(sim) |>
  summarise(across(everything(), mean)) |>
  select(-sim) |>
  summarise(across(everything(), \(x) med_iqr(x, fmtr))) |>
  as.character()

tbl <- rbind(tar, sim_vals, prms)
rownames(tbl) <- row_names
colnames(tbl) <- col_names

knitr::kable(tbl)
```

## Disease MR100 - section xx

```{r}
p <- calib_plot_infos[["disease.mr100"]]
make_calib_plot(d_outs, p)
```

```{r}
col_names <- "disease.mr100"
row_names <- c(
  "Target Statistic: disease mr100",
  "Simulations: disease mr100 (med [IQR])",
  "Calibrated aids.off.tx.mort.rate (per week)"
)

fmtr <- scales::label_number(0.1)
tar_names <- c("disease.mr100")
tar <- targets[tar_names] |> fmtr()
p_names <- c("aids.off.tx.mort.rate")
prms <- unlist(param[p_names]) |> scales::label_scientific()()

sim_vals <- d_outs |>
  filter(time > max(time) - year_steps) |>
  select(sim, all_of(tar_names)) |>
  group_by(sim) |>
  summarise(across(everything(), mean)) |>
  select(-sim) |>
  summarise(across(everything(), \(x) med_iqr(x, fmtr))) |>
  as.character()

tbl <- rbind(tar, sim_vals, prms)
rownames(tbl) <- row_names
colnames(tbl) <- col_names

knitr::kable(tbl)
```

## a.rate - section xx

```{r}
p <- calib_plot_infos[["num"]]
make_calib_plot(d_outs, p)
```

```{r}
col_names <- "num"
row_names <- c(
  "Target Statistic: num",
  "Simulations: num (med [IQR])",
  "Calibrated a.rate (per week)"
)

fmtr <- scales::label_number(1)
tar_names <- c("num")
tar <- 1e5 |> fmtr()
p_names <- c("a.rate")
prms <- unlist(param[p_names]) |> scales::label_scientific()()

sim_vals <- d_outs |>
  filter(time > max(time) - year_steps) |>
  select(sim, all_of(tar_names)) |>
  group_by(sim) |>
  summarise(across(everything(), mean)) |>
  select(-sim) |>
  summarise(across(everything(), \(x) med_iqr(x, fmtr))) |>
  as.character()

tbl <- rbind(tar, sim_vals, prms)
rownames(tbl) <- row_names
colnames(tbl) <- col_names

knitr::kable(tbl)
```
