---
title: "Calibration Values"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    number_sections: true
    smart: false
---

```{r setup, include = FALSE}
source("R/shared_variables.R", local = TRUE)

library(dplyr)
library(EpiModelHIV)

context <- "hpc"
source("R/netsim_settings.R", local = TRUE)

d_calib <- readRDS(fs::path(calib_dir, "merged_tibbles", "df__empty_scenario.rds"))

d_outs <- EpiModelHIV::mutate_calibration_targets(d_calib) |>
  mutate(sim = as.integer(as.factor(paste0(batch_number, "_", sim)))) |>
  as.epi.data.frame()

races <- c("B", "H", "W")
calib_plot_infos <- list(
  cc.dx = list(
    names = paste0("cc.dx.", races),
    ylab = "Proportion",
    text_offset = 0.01,
    fmt_target = scales::percent_format(0.1)
  ),
  cc.linked1m = list(
    names = paste0("cc.linked1m.", races),
    ylab = "Proportion",
    text_offset = 0.005,
    fmt_target = scales::percent_format(0.1)
  ),
  cc.vsupp = list(
    names = paste0("cc.vsupp.", races),
    ylab = "Proportion",
    text_offset = 0.005,
    fmt_target = scales::percent_format(0.1)
  ),
  i.prev.dx = list(
    names = paste0("i.prev.dx.", races),
    ylab = "Proportion",
    text_offset = 0.01,
    fmt_target = scales::percent_format(0.1)
  ),
  ir100.sti = list(
    names = c("ir100.gc", "ir100.ct"),
    ylab = "Infection Rate per 100 PYAR",
    text_offset = 0.3,
    fmt_target = scales::number_format(0.1)
  ),
  cc.prep = list(
    names = paste0("cc.prep.", races),
    ylab = "Proportion",
    text_offset = 0.005,
    fmt_target = scales::percent_format(0.1)
  ),
  disease.mr100 = list(
    names = "disease.mr100",
    ylab = "Proportion",
    text_offset = 0.01,
    fmt_target = scales::percent_format(0.1)
  ),
  num = list(
    names = "num",
    ylab = "Population",
    text_offset = 500,
    fmt_target = scales::number_format(1)
  )
)

make_calib_plot <- function(d, plot_info) {
  targets <- EpiModelHIV::get_calibration_targets()
  targets["num"] <- 1e5
  colors <-  c("steelblue", "firebrick", "seagreen")
  text_pos <- max(d$time) - 500
  par(mar = c(3, 3, 1, 1), mgp = c(2, 1, 0))
  offset <- plot_info$text_offset
  cur_targs <- plot_info$names

  plot(
    d,
    xaxt = "n",
    y = cur_targs,
    legend = TRUE,
    ylab = plot_info$ylab,
    xlab = "Calibration Years"
  )
  axis(1, seq(0, max(d$time), 10 * year_steps),
       labels = seq(0, max(d$time), 10 * year_steps) / year_steps)

  x <- round(colMeans(tail(d_outs[, cur_targs], 52)), 3)
  abline(h = targets[cur_targs], col = colors, lty = 2)
  for (i in seq_along(plot_info$names)) {
    v <- plot_info$fmt_target(x[i])
    text(text_pos, targets[cur_targs[i]] + offset, v, col = colors[i])
  }
}

targets <- EpiModelHIV::get_calibration_targets()
races_names <- c("B", "H", "W")
races <- 1:3

med_iqr <- function(x, fmtr) {
  vs <- quantile(x, c(0.5, 0.25, 0.75)) |> fmtr()
  paste0(vs[1], " [", vs[2], "-",  vs[3], "]")
}
```

## cc.dx - section 7.1

```{r}
p <- calib_plot_infos[["cc.dx"]]
make_calib_plot(d_outs, p)
```

```{r}
col_names <- paste0(c("Black", "Hispanic", "White/Other"), "MSM")
row_names <- c(
  "Target Statistic: Diagnosed Fraction",
  "Simulations: Diagnosed Fractions (med [IQR])",
  "Calibrated Rates (per Week)",
  "Mean Inter-Test Interval (Years)",
  "Median Diagnostic Delay (Years)"
)

fmtr <- scales::label_percent(0.1)
tar_names <- paste0("cc.dx.", races_names)
tar <- targets[tar_names] |> fmtr()
p_names <- paste0("hiv.test.rate")
prms <- param[[p_names]] |> scales::label_scientific()()
m_int <- (1 / param[[p_names]] / 52) |> scales::label_number(0.1)()
med_diag_delays <- d_outs |>
  filter(time > max(time) - year_steps) |>
  select(sim, starts_with("med_diag_delay_")) |>
  group_by(sim) |>
  summarise(across(everything(), mean)) |>
  select(-sim) |>
  mutate(across(everything(), \(x) x / year_steps)) |>
  summarise(across(everything(), \(x) med_iqr(x, scales::label_number(0.01)))) |>
  as.character()

sim_vals <- d_outs |>
  filter(time > max(time) - year_steps) |>
  select(sim, all_of(tar_names)) |>
  group_by(sim) |>
  summarise(across(everything(), mean)) |>
  select(-sim) |>
  summarise(across(everything(), \(x) med_iqr(x, fmtr))) |>
  as.character()



tbl <- rbind(tar, sim_vals,  prms, m_int, med_diag_delays)
rownames(tbl) <- row_names
colnames(tbl) <- col_names

knitr::kable(tbl)
```

## cc.linked1m - section 7.2

```{r}
p <- calib_plot_infos[["cc.linked1m"]]
make_calib_plot(d_outs, p)
```

```{r}
col_names <- paste0(c("Black", "Hispanic", "White/Other"), "MSM")
row_names <- c(
  "Target Statistic: Fraction Linked within 1m",
  "Simulations: Fraction Linked (med [IQR])",
  "Calibrated Rates (per Week)",
  "Mean Time to ART (in Weeks)"
)

fmtr <- scales::label_percent(0.1)
tar_names <- paste0("cc.linked1m.", races_names)
tar <- targets[tar_names] |> fmtr()
p_names <- paste0("tx.init.rate")
prms <- param[[p_names]] |> scales::label_scientific()()
mean_time_to_art <- scales::label_number(0.1)(1 / param[[p_names]])

sim_vals <- d_outs |>
  filter(time > max(time) - year_steps) |>
  select(sim, all_of(tar_names)) |>
  group_by(sim) |>
  summarise(across(everything(), mean)) |>
  select(-sim) |>
  summarise(across(everything(), \(x) med_iqr(x, fmtr))) |>
  as.character()

tbl <- rbind(tar, sim_vals,  prms, mean_time_to_art)
rownames(tbl) <- row_names
colnames(tbl) <- col_names

knitr::kable(tbl)
```

## cc.vsupp - section 7.3

```{r}
p <- calib_plot_infos[["cc.vsupp"]]
make_calib_plot(d_outs, p)
```

```{r}
col_names <- paste0(c("Black", "Hispanic", "White/Other"), "MSM")
row_names <- c(
  "Target Statistic: Fraction VL Suppressed",
  "Simulations: Fraction VL Suppressed (med [IQR])",
  "Calibrated Halting Rates (per Week)",
  "Mean Time to First ART Stoppage (in Weeks)",
  "Mean Time to First ART Stoppage (in Years)"
)

fmtr <- scales::label_percent(0.1)
tar_names <- paste0("cc.vsupp.", races_names)
tar <- targets[tar_names] |> fmtr()
p_names <- paste0("tx.halt.partial.rate")
prms <- param[[p_names]] |> scales::label_scientific()()
mean_time_stop_w <- scales::label_number(1)(1 / param[[p_names]])
mean_time_stop_y <- scales::label_number(0.1)(1 / param[[p_names]] / 52)


sim_vals <- d_outs |>
  filter(time > max(time) - year_steps) |>
  select(sim, all_of(tar_names)) |>
  group_by(sim) |>
  summarise(across(everything(), mean)) |>
  select(-sim) |>
  summarise(across(everything(), \(x) med_iqr(x, fmtr))) |>
  as.character()

tbl <- rbind(tar, sim_vals,  prms, mean_time_stop_w, mean_time_stop_y)
rownames(tbl) <- row_names
colnames(tbl) <- col_names

knitr::kable(tbl)
```

## i.prev.dx - section 8.2

```{r}
p <- calib_plot_infos[["i.prev.dx"]]
make_calib_plot(d_outs, p)
```

```{r}
col_names <- paste0(c("Black", "Hispanic", "White/Other"), "MSM")
row_names <- c(
  "Target Statistic: HIV Prevalence",
  "Simulations: HIV Prevalence (med [IQR])",
  "Transmission Scaler (per act)"
)

fmtr <- scales::label_percent(0.1)
tar_names <- paste0("i.prev.dx.", races_names)
tar <- targets[tar_names] |> fmtr()
p_names <- paste0("hiv.trans.scale")
prms <- param[[p_names]] |> scales::label_number(0.01)()

sim_vals <- d_outs |>
  filter(time > max(time) - year_steps) |>
  select(sim, all_of(tar_names)) |>
  group_by(sim) |>
  summarise(across(everything(), mean)) |>
  select(-sim) |>
  summarise(across(everything(), \(x) med_iqr(x, fmtr))) |>
  as.character()

tbl <- rbind(tar, sim_vals, prms)
rownames(tbl) <- row_names
colnames(tbl) <- col_names

knitr::kable(tbl)
```

## cc.prep - section xx

```{r}
p <- calib_plot_infos[["cc.prep"]]
make_calib_plot(d_outs, p)
```

```{r}
col_names <- paste0(c("Black", "Hispanic", "White/Other"), "MSM")
row_names <- c(
  "Target Statistic: PrEP Coverage",
  "Simulations: PrEP Coverage (med [IQR])",
  "Calibrated PrEP Rates (per Week)"
)

fmtr <- scales::label_percent(0.1)
tar_names <- paste0("cc.prep.", races_names)
tar <- targets[tar_names] |> fmtr()
p_names <- paste0("prep.start.prob")
prms <- param[[p_names]] |> scales::label_scientific()()

sim_vals <- d_outs |>
  filter(time > max(time) - year_steps) |>
  select(sim, all_of(tar_names)) |>
  group_by(sim) |>
  summarise(across(everything(), mean)) |>
  select(-sim) |>
  summarise(across(everything(), \(x) med_iqr(x, fmtr))) |>
  as.character()

tbl <- rbind(tar, sim_vals, prms)
rownames(tbl) <- row_names
colnames(tbl) <- col_names

knitr::kable(tbl)
```

## STI - section xx

```{r}
p <- calib_plot_infos[["ir100.sti"]]
make_calib_plot(d_outs, p)
```

```{r}
col_names <- paste0(c("GC", "CT"), " IR100")
row_names <- c(
  "Target Statistic: STI IR100",
  "Simulations: STI IR100 (med [IQR])",
  "Calibrated Transmission Urethral Probability (per act)"
)

fmtr <- scales::label_number(0.1)
tar_names <- c("ir100.gc", "ir100.ct")
tar <- targets[tar_names] |> fmtr()
p_names <- c("ugc.prob", "uct.prob")
prms <- unlist(param[p_names]) |> scales::label_number(0.01)()

sim_vals <- d_outs |>
  filter(time > max(time) - year_steps) |>
  select(sim, all_of(tar_names)) |>
  group_by(sim) |>
  summarise(across(everything(), mean)) |>
  select(-sim) |>
  summarise(across(everything(), \(x) med_iqr(x, fmtr))) |>
  as.character()

tbl <- rbind(tar, sim_vals, prms)
rownames(tbl) <- row_names
colnames(tbl) <- col_names

knitr::kable(tbl)
```

## Disease MR100 - section xx

```{r}
p <- calib_plot_infos[["disease.mr100"]]
make_calib_plot(d_outs, p)
```

```{r}
col_names <- "disease.mr100"
row_names <- c(
  "Target Statistic: disease mr100",
  "Simulations: disease mr100 (med [IQR])",
  "Calibrated aids.off.tx.mort.rate (per week)"
)

fmtr <- scales::label_number(0.1)
tar_names <- c("disease.mr100")
tar <- targets[tar_names] |> fmtr()
p_names <- c("aids.off.tx.mort.rate")
prms <- unlist(param[p_names]) |> scales::label_scientific()()

sim_vals <- d_outs |>
  filter(time > max(time) - year_steps) |>
  select(sim, all_of(tar_names)) |>
  group_by(sim) |>
  summarise(across(everything(), mean)) |>
  select(-sim) |>
  summarise(across(everything(), \(x) med_iqr(x, fmtr))) |>
  as.character()

tbl <- rbind(tar, sim_vals, prms)
rownames(tbl) <- row_names
colnames(tbl) <- col_names

knitr::kable(tbl)
```

## a.rate - section xx

```{r}
p <- calib_plot_infos[["num"]]
make_calib_plot(d_outs, p)
```

```{r}
col_names <- "num"
row_names <- c(
  "Target Statistic: num",
  "Simulations: num (med [IQR])",
  "Calibrated a.rate (per week)"
)

fmtr <- scales::label_number(1)
tar_names <- c("num")
tar <- 1e5 |> fmtr()
p_names <- c("a.rate")
prms <- unlist(param[p_names]) |> scales::label_scientific()()

sim_vals <- d_outs |>
  filter(time > max(time) - year_steps) |>
  select(sim, all_of(tar_names)) |>
  group_by(sim) |>
  summarise(across(everything(), mean)) |>
  select(-sim) |>
  summarise(across(everything(), \(x) med_iqr(x, fmtr))) |>
  as.character()

tbl <- rbind(tar, sim_vals, prms)
rownames(tbl) <- row_names
colnames(tbl) <- col_names

knitr::kable(tbl)
```

