[workspace]
authors = ["Adrien Le Guillou <git@aleguillou.org>"]
channels = ["conda-forge"]
name = "EpiModelHIV-Template"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
r = ">=4.5,<4.6"
r-languageserver = ">=0.3.18,<0.4"
r-devtools = ">=2.5.2,<3"
r-renv = ">=1.2.2,<2"
r-dplyr = ">=1.2.1,<2"
r-ggplot2 = ">=4.0.3,<5"
r-rcpp = ">=1.1.1_1.1,<2"
r-rlang = ">=1.2.0,<2"
r-tidyr = ">=1.3.2,<2"
r-microbenchmark = ">=1.5.0,<2"
r-bench = ">=1.1.4,<2"
r-lobstr = ">=1.2.1,<2"
r-pak = ">=0.9.5,<0.10"
r-usethis = ">=3.2.1,<4"
r-igraph = ">=2.3.1,<3"
r-progressr = ">=0.19.0,<0.20"
r-ape = ">=5.8_1,<6"
r-coda = ">=0.19_4.1,<0.20"
r-desolve = ">=1.42,<2"
r-future = ">=1.70.0,<2"
"r-future.apply" = ">=1.20.2,<2"
r-globals = ">=0.19.1,<0.20"
r-listenv = ">=0.10.1,<0.11"
r-lpsolveapi = ">=5.5.2.0_17.15,<6"
r-parallelly = ">=1.47.0,<2"
r-rbibutils = ">=2.4.1,<3"
r-robustbase = ">=0.99_7,<0.100"
r-trust = ">=0.1_9,<0.2"
r-rdpack = ">=2.6.6,<3"
r-rle = ">=0.10.0,<0.11"
pdflatex = ">=0.1.3,<0.2"
r-doparallel = ">=1.0.17,<2"
r-foreach = ">=1.5.2,<2"
r-iterators = ">=1.0.14,<2"
r-lhs = ">=1.3.0,<2"
r-viridis = ">=0.6.5,<0.7"
